//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Futon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ad
    {
        public int Id { get; set; }
        public string Photo { get; set; }
        public string Url { get; set; }
        public Nullable<int> LocationId { get; set; }
    
        public virtual AdLocation AdLocation { get; set; }
    }
}
